In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("emails_checked.csv")

In [3]:
df

,Sno,Name,Email,Title,Company,Status,Sent
0,1,Sir/Ma'am,talent@metastart.in,NaN,Metastart,unknown,Yes
1,2,Sir/Ma'am,utkarsh@userfindr.com,NaN,Userfindr,not exist,Yes
2,3,Sir/Ma'am,debasmita.roy@astrotalk.com,NaN,Astrotalk,unknown,Yes
3,4,Sir/Ma'am,hiring@astrotalk.com,NaN,Astrotalk,unknown,Yes
4,5,Sir/Ma'am,talent@humantic.ai,NaN,Humantic AI,unknown,Yes
...,...,...,...,...,...,...,...
216,217,Sir/Ma'am,resume@multitech.co.in,NaN,MultiTech,not exist,NaN
217,218,Sir/Ma'am,reach@vsnl.com,NaN,Reach Consulting,not exist,NaN
218,219,Sir/Ma'am,jobs@nexageconsulting.com,NaN,NexAge Consulting,not exist,NaN
219,220,Sir/Ma'am,jkconsultants@vsnl.com,NaN,JK Consultants,not exist,NaN
220,221,Sir/Ma'am,consulti@vsnl.com,NaN,Consulti,not exist,NaN

In [4]:
df['Status'].value_counts()

Status
unknown      131
not exist     90
Name: count, dtype: int64

In [5]:
df = df[df["Status"] != "not exist"]

In [6]:
df

,Sno,Name,Email,Title,Company,Status,Sent
0,1,Sir/Ma'am,talent@metastart.in,NaN,Metastart,unknown,Yes
2,3,Sir/Ma'am,debasmita.roy@astrotalk.com,NaN,Astrotalk,unknown,Yes
3,4,Sir/Ma'am,hiring@astrotalk.com,NaN,Astrotalk,unknown,Yes
4,5,Sir/Ma'am,talent@humantic.ai,NaN,Humantic AI,unknown,Yes
5,6,Sir/Ma'am,support@medstown.com,NaN,Medstown,unknown,Yes
...,...,...,...,...,...,...,...
209,210,Sir/Ma'am,resume_india@intergraph.com,NaN,Intergraph,unknown,NaN
211,212,Sir/Ma'am,career@hiso.honeywell.com,NaN,Honeywell,unknown,NaN
212,213,Sir/Ma'am,hrssg@teil.soft.net,NaN,TEIL,unknown,NaN
213,214,Sir/Ma'am,careers@cmg.nu,NaN,CMG,unknown,NaN
215,216,Sir/Ma'am,general@cominsights.com,NaN,ComInsights,unknown,NaN

In [7]:
df = df.drop(columns=['Status', 'Sent'])

In [8]:
df.to_csv("emails_final.csv", index=False)